'use client';
import { useMemo, useState } from 'react';
import { RepairCategory, RepairUrgency, AnalysisPayload } from '@/types/repair';
export default function UploadForm(){const[file,setFile]=useState<File|null>(null);const[email,setEmail]=useState('');const[description,setDescription]=useState('');const[category,setCategory]=useState<RepairCategory>('general');const[urgency,setUrgency]=useState<RepairUrgency>('minor');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[analysis,setAnalysis]=useState<AnalysisPayload|null>(null);const[requestId,setRequestId]=useState('');const previewUrl=useMemo(()=>file?URL.createObjectURL(file):'',[file]);async function handleAnalyze(){try{setLoading(true);setError('');setAnalysis(null);if(!file)throw new Error('Please upload a photo.');if(!email)throw new Error('Please enter an email.');const formData=new FormData();formData.append('photo',file);formData.append('email',email);formData.append('description',description);formData.append('category',category);formData.append('urgency',urgency);const response=await fetch('/api/analyze',{method:'POST',body:formData});const data=await response.json();if(!response.ok)throw new Error(data.error||'Analysis failed.');setAnalysis(data.analysis);setRequestId(data.requestId)}catch(err){setError(err instanceof Error?err.message:'Something went wrong.')}finally{setLoading(false)}}async function handleCheckout(){try{if(!analysis||!requestId)throw new Error('Run the analysis first.');const res = await fetch('/api/create-checkout', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    repairRequestId: requestId,
    amount: analysis.review_price_cents,
    origin: window.location.origin,
  }),
})

const data = await res.json()

window.location.href = data.url;if(Response)throw new Error(data.error||'Checkout failed.');window.location.href=data.url}catch(err){setError(err instanceof Error?err.message:'Checkout failed.')}}return <div className="grid grid-2"><div className="card"><h2>Describe the issue</h2><div className="small">Upload a clear photo and tell FixLens what you are seeing.</div><div style={{height:12}}/><input type="file" accept="image/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><div style={{height:12}}/>{previewUrl?<img className="preview" src={previewUrl} alt="Preview"/>:null}<div style={{height:12}}/><input value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email"/><div style={{height:12}}/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Describe the problem"/><div style={{height:12}}/><select value={category} onChange={e=>setCategory(e.target.value as RepairCategory)}><option value="general">General</option><option value="plumbing">Plumbing</option><option value="electrical">Electrical</option><option value="hvac">HVAC</option><option value="drywall">Drywall</option><option value="appliance">Appliance</option></select><div style={{height:12}}/><select value={urgency} onChange={e=>setUrgency(e.target.value as RepairUrgency)}><option value="minor">Minor</option><option value="moderate">Moderate</option><option value="urgent">Urgent</option></select><div style={{height:12}}/><button onClick={handleAnalyze} disabled={loading}>{loading?'Analyzing...':'Upload and analyze'}</button>{error?<p className="small" style={{color:'#b91c1c'}}>{error}</p>:null}</div><div className="card"><h2>AI assessment</h2>{!analysis?<p className="small">Your analysis will appear here after upload.</p>:<><p>{analysis.summary}</p><h3>Image findings</h3><ul>{analysis.image_findings.map(x=><li key={x}>{x}</li>)}</ul><h3>Possible causes</h3><ul>{analysis.possible_causes.map(x=><li key={x}>{x}</li>)}</ul><h3>Safe first steps</h3><ul>{analysis.safe_first_steps.map(x=><li key={x}>{x}</li>)}</ul><p><strong>Difficulty:</strong> {analysis.difficulty}</p><p><strong>Estimated cost:</strong> {analysis.estimated_cost_range}</p><p><strong>Safety note:</strong> {analysis.safety_note}</p><p><strong>Recommendation:</strong> {analysis.recommendation}</p><button onClick={handleCheckout}>Buy professional review (${(analysis.review_price_cents/100).toFixed(0)})</button></>}</div></div>}
